@isTest
public class ACCC_wwwViadComSecurityV2Vaccc_Test { 
    public static testMethod void testmethod1() {
        ACCC_wwwViadComSecurityV2.EndAppSession_element endAppSession = new ACCC_wwwViadComSecurityV2.EndAppSession_element();
        ACCC_wwwViadComSecurityV2.UserLogoutResponse_element UserLogoutResponse = new ACCC_wwwViadComSecurityV2.UserLogoutResponse_element();
        ACCC_wwwViadComSecurityV2.SearchDirectory_element SearchDirectory = new ACCC_wwwViadComSecurityV2.SearchDirectory_element();
        ACCC_wwwViadComSecurityV2.UserLogout_element UserLogout_element = new ACCC_wwwViadComSecurityV2.UserLogout_element();
        ACCC_wwwViadComSecurityV2.RequestSessionTransferResponse_element RequestSessionTransferResponse_element = new ACCC_wwwViadComSecurityV2.RequestSessionTransferResponse_element();
        ACCC_wwwViadComSecurityV2.UpdateEmailAddressResponse_element UpdateEmailAddressResponse_element = new ACCC_wwwViadComSecurityV2.UpdateEmailAddressResponse_element();
        ACCC_wwwViadComSecurityV2.UpdateContactInformationResponse_element UpdateContactInformationResponse_element = new ACCC_wwwViadComSecurityV2.UpdateContactInformationResponse_element();
        ACCC_wwwViadComSecurityV2.UserLoginByDomain_element UserLoginByDomain_element = new ACCC_wwwViadComSecurityV2.UserLoginByDomain_element();
        
        ACCC_wwwViadComSecurityV2.RequestSessionTransfer_element RequestSessionTransfer_element = new ACCC_wwwViadComSecurityV2.RequestSessionTransfer_element();
        ACCC_wwwViadComSecurityV2.AppSessionInfo AppSessionInfo = new ACCC_wwwViadComSecurityV2.AppSessionInfo();
        ACCC_wwwViadComSecurityV2.UserInfo UserInfo = new ACCC_wwwViadComSecurityV2.UserInfo();
        ACCC_wwwViadComSecurityV2.TransferSession_element TransferSession_element = new ACCC_wwwViadComSecurityV2.TransferSession_element();
        ACCC_wwwViadComSecurityV2.RetrieveContactInformationResponse_element RetrieveContactInformationResponse_element = new ACCC_wwwViadComSecurityV2.RetrieveContactInformationResponse_element();
        ACCC_wwwViadComSecurityV2.UpdateDisplayNameResponse_element  UpdateDisplayNameResponse_element = new ACCC_wwwViadComSecurityV2.UpdateDisplayNameResponse_element();
        ACCC_wwwViadComSecurityV2.QuerySession_element QuerySession_element = new ACCC_wwwViadComSecurityV2.QuerySession_element();
        ACCC_wwwViadComSecurityV2.UpdateContactInformation_element UpdateContactInformation_element = new ACCC_wwwViadComSecurityV2.UpdateContactInformation_element();
		ACCC_wwwViadComSecurityV2.QuerySessionThisNode_element QuerySessionThisNode_element = new ACCC_wwwViadComSecurityV2.QuerySessionThisNode_element();
		ACCC_wwwViadComSecurityV2.SyncSessionFromOtherNode_element SyncSessionFromOtherNode_element = new ACCC_wwwViadComSecurityV2.SyncSessionFromOtherNode_element();
        
        ACCC_wwwViadComSecurityV2.StartAppSessionResponse_element StartAppSessionResponse_element = new ACCC_wwwViadComSecurityV2.StartAppSessionResponse_element();
        ACCC_wwwViadComSecurityV2.TransferSessionResponse_element  TransferSessionResponse_element  = new ACCC_wwwViadComSecurityV2.TransferSessionResponse_element();
        ACCC_wwwViadComSecurityV2.UserLoginResponse_element  UserLoginResponse_element  = new ACCC_wwwViadComSecurityV2.UserLoginResponse_element();
        ACCC_wwwViadComSecurityV2.ResetPasswordRequestInfo  ResetPasswordRequestInfo  = new ACCC_wwwViadComSecurityV2.ResetPasswordRequestInfo ();
        ACCC_wwwViadComSecurityV2.UserLogin_element  UserLogin_element  = new ACCC_wwwViadComSecurityV2.UserLogin_element();
        ACCC_wwwViadComSecurityV2.UserLoginWithoutPasswordResponse_element   UserLoginWithoutPasswordResponse_element  = new ACCC_wwwViadComSecurityV2.UserLoginWithoutPasswordResponse_element();
        ACCC_wwwViadComSecurityV2.ArrayOfDirectoryInfo  ArrayOfDirectoryInfo  = new ACCC_wwwViadComSecurityV2.ArrayOfDirectoryInfo ();
        ACCC_wwwViadComSecurityV2.ResetPassword_element  ResetPassword_element  = new ACCC_wwwViadComSecurityV2.ResetPassword_element ();
        
        ACCC_wwwViadComSecurityV2.ResetPasswordResponse_element  ResetPasswordResponse_element  = new ACCC_wwwViadComSecurityV2.ResetPasswordResponse_element ();
        ACCC_wwwViadComSecurityV2.DomainInfo   DomainInfo   = new ACCC_wwwViadComSecurityV2.DomainInfo ();
        ACCC_wwwViadComSecurityV2.ContactInfo   ContactInfo   = new ACCC_wwwViadComSecurityV2.ContactInfo ();
        ACCC_wwwViadComSecurityV2.SearchDirectoryResponse_element   SearchDirectoryResponse_element   = new ACCC_wwwViadComSecurityV2.SearchDirectoryResponse_element  ();
        ACCC_wwwViadComSecurityV2.UserLoginWithStoredPasswordResponse_element   UserLoginWithStoredPasswordResponse_element   = new ACCC_wwwViadComSecurityV2.UserLoginWithStoredPasswordResponse_element ();
        ACCC_wwwViadComSecurityV2.UserLoginWithStoredPassword_element    UserLoginWithStoredPassword_element   = new ACCC_wwwViadComSecurityV2.UserLoginWithStoredPassword_element ();
        ACCC_wwwViadComSecurityV2.QuerySessionResponse_element   QuerySessionResponse_element   = new ACCC_wwwViadComSecurityV2.QuerySessionResponse_element  ();
        ACCC_wwwViadComSecurityV2.ArrayOfResetPasswordRequestInfo   ArrayOfResetPasswordRequestInfo   = new ACCC_wwwViadComSecurityV2.ArrayOfResetPasswordRequestInfo  ();
        
        ACCC_wwwViadComSecurityV2.UserLoginWithoutPassword_element   UserLoginWithoutPassword_element   = new ACCC_wwwViadComSecurityV2.UserLoginWithoutPassword_element  ();
        ACCC_wwwViadComSecurityV2.UpdateEmailAddress_element    UpdateEmailAddress_element    = new ACCC_wwwViadComSecurityV2.UpdateEmailAddress_element  ();
        ACCC_wwwViadComSecurityV2.UserLoginByDomainResponse_element    UserLoginByDomainResponse_element    = new ACCC_wwwViadComSecurityV2.UserLoginByDomainResponse_element  ();
        ACCC_wwwViadComSecurityV2.UpdateDisplayName_element    UpdateDisplayName_element    = new ACCC_wwwViadComSecurityV2.UpdateDisplayName_element   ();
        ACCC_wwwViadComSecurityV2.EndAppSessionResponse_element    EndAppSessionResponse_element    = new ACCC_wwwViadComSecurityV2.EndAppSessionResponse_element  ();
        ACCC_wwwViadComSecurityV2.QueryOtherSession_element     QueryOtherSession_element    = new ACCC_wwwViadComSecurityV2.QueryOtherSession_element  ();
        ACCC_wwwViadComSecurityV2.RetrieveContactInformation_element    RetrieveContactInformation_element    = new ACCC_wwwViadComSecurityV2.RetrieveContactInformation_element   ();
        ACCC_wwwViadComSecurityV2.StartAppSession_element    StartAppSession_element    = new ACCC_wwwViadComSecurityV2.StartAppSession_element   ();
        
        ACCC_wwwViadComSecurityV2.ResetPasswordRequestResponse_element    ResetPasswordRequestResponse_element    = new ACCC_wwwViadComSecurityV2.ResetPasswordRequestResponse_element   ();
        ACCC_wwwViadComSecurityV2.DirectoryInfo     DirectoryInfo     = new ACCC_wwwViadComSecurityV2.DirectoryInfo   ();
        ACCC_wwwViadComSecurityV2.CreateAccount_element     CreateAccount_element     = new ACCC_wwwViadComSecurityV2.CreateAccount_element   ();
        ACCC_wwwViadComSecurityV2.CreateAccountResponse_element     CreateAccountResponse_element     = new ACCC_wwwViadComSecurityV2.CreateAccountResponse_element    ();
        ACCC_wwwViadComSecurityV2.ResetPasswordRequest_element     ResetPasswordRequest_element     = new ACCC_wwwViadComSecurityV2.ResetPasswordRequest_element   ();
        ACCC_wwwViadComSecurityV2.QueryOtherSessionResponse_element      QueryOtherSessionResponse_element     = new ACCC_wwwViadComSecurityV2.QueryOtherSessionResponse_element   ();
		ACCC_wwwViadComSecurityV2.QuerySessionThisNodeResponse_element      QuerySessionThisNodeResponse_element     = new ACCC_wwwViadComSecurityV2.QuerySessionThisNodeResponse_element   ();
		ACCC_wwwViadComSecurityV2.SyncSessionFromOtherNodeResponse_element      SyncSessionFromOtherNodeResponse_element     = new ACCC_wwwViadComSecurityV2.SyncSessionFromOtherNodeResponse_element   ();
        ACCC_wwwViadComSecurityV2.ArrayOfDomainInfo     ArrayOfDomainInfo     = new ACCC_wwwViadComSecurityV2.ArrayOfDomainInfo    ();
        
        ACCC_wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService     BasicHttpBinding_IAuthenticationService     = new ACCC_wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService    ();
       Test.setMock(WebServiceMock.class, new ACCC_wwwViadComSecurityV2Vaccc_Mock());
        BasicHttpBinding_IAuthenticationService.ResetPasswordRequest('testlogin', 'testlogin', 'test@test.com');
        BasicHttpBinding_IAuthenticationService.UserLoginWithoutPassword('testlogin','test@test.com', true);
        BasicHttpBinding_IAuthenticationService.StartAppSession('testlogin','test@test.com', 'true','test');
        BasicHttpBinding_IAuthenticationService.RetrieveContactInformation('testlogin');       
        BasicHttpBinding_IAuthenticationService.SearchDirectory('testlogin','testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.UserLogin ('testlogin','testlogin','testlogin', true);
        BasicHttpBinding_IAuthenticationService.UserLoginWithStoredPassword ('testlogin','testlogin','testlogin','password', true);
        BasicHttpBinding_IAuthenticationService.TransferSession ('testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.ResetPassword ('testlogin','testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.UpdateEmailAddress ('testlogin','testlogin@test.com');
        BasicHttpBinding_IAuthenticationService.UpdateDisplayName ('testlogin','Rahul');
        BasicHttpBinding_IAuthenticationService.QuerySession ('testlogin');
        BasicHttpBinding_IAuthenticationService.UserLoginByDomain ('testlogin','Rahul','loginName','password',true);
        BasicHttpBinding_IAuthenticationService.QueryOtherSession ('testlogin','Rahul');
		//BasicHttpBinding_IAuthenticationService.SyncSessionFromOtherNode ('testlogin');
		BasicHttpBinding_IAuthenticationService.QuerySessionThisNode ('testlogin');
		BasicHttpBinding_IAuthenticationService.UserLogout ('testlogin');
		//BasicHttpBinding_IAuthenticationService.GetDomainStatuses ('testlogin'); 

                
    } 
}