global class Properties
{
    global final static String kiosk = 'KIOSK';
    global final static String construction = 'CONSTRUCTION';
    global final static String intl = 'INTL';
    global final static String graphics = 'GRAPHICS';    
    global final static String refurb = 'REFURB';   
    global final static String exhibit = 'EXHIBIT';   

    global final static String edProjectsRecordTypeName = 'E&D - Projects';
    global final static String edProjectsProposalRecordTypeName = 'E&D - Projects - Proposal';
    global final static String edProjectsReadOnlyRecordTypeName = 'E&D - Projects - Read Only';
}