@isTest
public class schemasDatacontractOrg200407SystemTest {
        public DateTime DateTime_x;
        public Integer OffsetMinutes;
        private Static String[] DateTime_x_type_info;
        private Static String[] OffsetMinutes_type_info; 
        private Static String[] apex_schema_type_info;
        private Static String[] field_order_type_info;
@isTest    
Private Static void  DateTimeOffset() {
      //schemasDatacontractOrg200407System obj=new schemasDatacontractOrg200407System();
      schemasDatacontractOrg200407System.DateTimeOffset dateTimeoffset=new schemasDatacontractOrg200407System.DateTimeOffset();
      dateTimeoffset.DateTime_x_type_info = new String[]{'2017-10-30 03:20:10','http://schemas.datacontract.org/2004/07/System',null,'1','1','false'};
      dateTimeoffset.OffsetMinutes_type_info = new String[]{'2017-09-30 03:20:10','http://schemas.datacontract.org/2004/07/System',null,'1','1','false'};
      dateTimeoffset.apex_schema_type_info = new String[]{'http://schemas.datacontract.org/2004/07/System','true','false'};
      dateTimeoffset.field_order_type_info = new String[]{'DateTime_x','OffsetMinutes'};
    }
}