@isTest
public class Show_Combined_Test {
    public static testMethod void testMethods(){
        ShowSer_DatacontractOrg200407System testShowSer_DatacontractOrg200407System=new ShowSer_DatacontractOrg200407System();
        ShowSer_DatacontractOrg200407System.DateTimeOffset testDateTimeOffset =new ShowSer_DatacontractOrg200407System.DateTimeOffset();
        ShowSer_MicrosoftCom200310Serializat testShowSer_MicrosoftCom200310Serializat=new ShowSer_MicrosoftCom200310Serializat();
        ShowSer_MicrosoftCom200310Serializat.ArrayOfstring testArrayOfstring =new ShowSer_MicrosoftCom200310Serializat.ArrayOfstring();
        ShowSer_MicrosoftCom200310Serializat.KeyValueOfstringstring_element  testKeyValueOfstringstring_element  =new ShowSer_MicrosoftCom200310Serializat.KeyValueOfstringstring_element();
        ShowSer_MicrosoftCom200310Serializat.ArrayOfKeyValueOfstringstring  testArrayOfKeyValueOfstringstring  =new ShowSer_MicrosoftCom200310Serializat.ArrayOfKeyValueOfstringstring();
        ShowSer_MicrosoftCom200310Serializat.ArrayOfint  testArrayOfint  =new ShowSer_MicrosoftCom200310Serializat.ArrayOfint();
        Show_MicrosoftCom200310Serializat testShow_MicrosoftCom200310Serializat=new Show_MicrosoftCom200310Serializat();
        Show_MicrosoftCom200310Serializat.ArrayOfstring  testobjArrayOfstring =new Show_MicrosoftCom200310Serializat.ArrayOfstring(); 
        Show_MicrosoftCom200310Serializat.KeyValueOfstringstring_element   testobjKeyValueOfstringstring_element  =new Show_MicrosoftCom200310Serializat.KeyValueOfstringstring_element(); 
        Show_MicrosoftCom200310Serializat.ArrayOfKeyValueOfstringstring   testobjArrayOfKeyValueOfstringstring  =new Show_MicrosoftCom200310Serializat.ArrayOfKeyValueOfstringstring(); 
        Show_MicrosoftCom200310Serializat.ArrayOfint   testobjArrayOfint  =new Show_MicrosoftCom200310Serializat.ArrayOfint(); 
        del_schemasDatacontractOrg200407System testdel_schemasDatacontractOrg200407System=new del_schemasDatacontractOrg200407System();
        del_schemasDatacontractOrg200407System.DateTimeOffset tesDateTimeOffset=new del_schemasDatacontractOrg200407System.DateTimeOffset();
        del_schemasMicrosoftCom200310Serializat testdel_schemasMicrosoftCom200310Serializat=new del_schemasMicrosoftCom200310Serializat();
        del_schemasMicrosoftCom200310Serializat.KeyValueOfstringstring_element KeyValueOfstringstring_element =new del_schemasMicrosoftCom200310Serializat.KeyValueOfstringstring_element();
         del_schemasMicrosoftCom200310Serializat.ArrayOfKeyValueOfstringstring  ArrayOfKeyValueOfstringstring  =new del_schemasMicrosoftCom200310Serializat.ArrayOfKeyValueOfstringstring();
        del_schemasMicrosoftCom200310Serializat.ArrayOfint ArrayOfint =new del_schemasMicrosoftCom200310Serializat.ArrayOfint();

    }
}