@isTest
public class SQR_Combined_Test {
    public static testMethod void testMethods(){
        SQR_schemasDatacontractOrg200407ViadSe testObj=new SQR_schemasDatacontractOrg200407ViadSe();
        SQR_schemasDatacontractOrg200407ViadSe.OrderSubmissionFault testOrderSubmissionFault=new SQR_schemasDatacontractOrg200407ViadSe.OrderSubmissionFault();
        SQR_schemasDatacontractOrg200407ViadSe.OrderPaymentProcessingFault testOrderPaymentProcessingFault=new  SQR_schemasDatacontractOrg200407ViadSe.OrderPaymentProcessingFault();
        SQR_schemasMicrosoftCom200310Arr testschemasMicrosoftCom=new SQR_schemasMicrosoftCom200310Arr();
        SQR_schemasMicrosoftCom200310Arr.ArrayOfstring tetsArrayOfstring =new  SQR_schemasMicrosoftCom200310Arr.ArrayOfstring();
        SQR_schemasMicrosoftCom200310Arr.KeyValueOfstringstring_element testKeyValueOfstringstring_element=new   SQR_schemasMicrosoftCom200310Arr.KeyValueOfstringstring_element();
        SQR_schemasMicrosoftCom200310Arr.ArrayOfKeyValueOfstringstring  testArrayOfKeyValueOfstringstring=new SQR_schemasMicrosoftCom200310Arr.ArrayOfKeyValueOfstringstring();
        SQR_schemasMicrosoftCom200310Arr.ArrayOfint testArrayOfint =new SQR_schemasMicrosoftCom200310Arr.ArrayOfint();
        SQR_schemasMicrosoftCom200310Serializat testschemasMicrosoftCom200310Serializat=new SQR_schemasMicrosoftCom200310Serializat();
        SQR_wwwViadComDataV1 testwwwViadComDataV1=new SQR_wwwViadComDataV1();
        SQR_wwwViadComDataV1.ArrayOfOrderComposite testArrayOfOrderComposite=new SQR_wwwViadComDataV1.ArrayOfOrderComposite();
        SQR_wwwViadComDataV1.OrderHeader  testOrderHeader =new SQR_wwwViadComDataV1.OrderHeader();
        SQR_wwwViadComDataV1.ArrayOfOrderPaymentInfoDetail  testArrayOfOrderPaymentInfoDetail =new SQR_wwwViadComDataV1.ArrayOfOrderPaymentInfoDetail();
        SQR_wwwViadComDataV1.ArrayOfCreateOrderLine  testArrayOfCreateOrderLine =new SQR_wwwViadComDataV1.ArrayOfCreateOrderLine();
        SQR_wwwViadComDataV1.CreateOrderLine  testCreateOrderLine =new SQR_wwwViadComDataV1.CreateOrderLine();
        SQR_wwwViadComDataV1.CreateOrderRequest  testCreateOrderRequest =new SQR_wwwViadComDataV1.CreateOrderRequest();
        SQR_wwwViadComDataV1.OrderBoothUpdate   testOrderBoothUpdate  =new SQR_wwwViadComDataV1.OrderBoothUpdate();
        SQR_wwwViadComDataV1.CreateOrderHeader  testCreateOrderHeader =new SQR_wwwViadComDataV1.CreateOrderHeader();
        SQR_wwwViadComDataV1.CreditCard  testCreditCard =new SQR_wwwViadComDataV1.CreditCard();
        SQR_wwwViadComDataV1.GetOrderAndSqrCountsResp  testGetOrderAndSqrCountsResp =new SQR_wwwViadComDataV1.GetOrderAndSqrCountsResp();
        SQR_wwwViadComDataV1.OrderLine   testOrderLine  =new SQR_wwwViadComDataV1.OrderLine();
        SQR_wwwViadComDataV1.OrderPaymentInfoDetail   testOrderPaymentInfoDetail  =new SQR_wwwViadComDataV1.OrderPaymentInfoDetail();
        SQR_wwwViadComDataV1.ArrayOfOrderHold   testArrayOfOrderHold  =new SQR_wwwViadComDataV1.ArrayOfOrderHold ();
        SQR_wwwViadComDataV1.OrderComposite    testOrderComposite   =new SQR_wwwViadComDataV1.OrderComposite();
        SQR_wwwViadComDataV1.OrderHold    testOrderHold   =new SQR_wwwViadComDataV1.OrderHold();
        SQR_wwwViadComDataV1.CreateOrderResponse   testCreateOrderResponse  =new SQR_wwwViadComDataV1.CreateOrderResponse();
        SQR_wwwViadComDataV1.OrderPaymentInfo    testOrderPaymentInfo   =new SQR_wwwViadComDataV1.OrderPaymentInfo();
        SQR_wwwViadComDataV1.CreditCardSubmission     testCreditCardSubmission    =new SQR_wwwViadComDataV1.CreditCardSubmission();
        SQR_wwwViadComDataV1.UpdateOrderPaymentRequest     testUpdateOrderPaymentRequest    =new SQR_wwwViadComDataV1.UpdateOrderPaymentRequest();
        SQR_wwwViadComDataV1.ArrayOfOrderLine     testArrayOfOrderLine    =new SQR_wwwViadComDataV1.ArrayOfOrderLine();
        
    }
    
}