public class TriggerOptimizationUtility {

    public static Set<Id> SetDataFromAccountReferences_Handled = new Set<Id>();
    
    public static Set<Id> ShowLOBDetails_Handled = new Set<Id>();
    
    public static Set<Id> UpdateOccurrenceDetails_Handled = new Set<Id>();
    
    
    public static Set<Id> trgUpdateOpportunityFields_Handled = new Set<Id>();
    
    public static Set<Id> trg_Update_Showplan_New_Handled = new Set<Id>();
    
    public static Set<Id> trgOpportunitySubmitForApproval_Handled = new Set<Id>();
    
    public static Set<Id> RollUpSummary_Handled = new Set<Id>();
    
    public static Set<Id> trg_upd_oppname_show_Handled = new Set<Id>();
    
    public static Set<Id> ShowAll_Handled = new Set<Id>();
    
    public static Set<Id> trg_upd_oppname_facility_Handled = new Set<Id>();

    public static Set<Id> trg_upd_oppname_relatedOpps = new Set<Id>();

    public static Set<Id> trg_opp_submit_for_approval = new Set<Id>();

    public static Set<Id> trg_opp_naming = new Set<Id>();

}