@isTest
public class UpSQR_ViadComDataV2_Test {
    public static testMethod void testMethods(){
        UpSQR_ViadComDataV2 testObj=new UpSQR_ViadComDataV2();
        UpSQR_ViadComDataV2.SqrHeader  SqrHeader =new UpSQR_ViadComDataV2.SqrHeader();
        UpSQR_ViadComDataV2.ArrayOfSqrHeader   ArrayOfSqrHeader  =new UpSQR_ViadComDataV2.ArrayOfSqrHeader();
/*
        UpSQR_ViadComDataV2.SqrItem SqrItem=new UpSQR_ViadComDataV2.SqrItem();
        UpSQR_ViadComDataV2.SqrItemProblem  SqrItemProblem =new UpSQR_ViadComDataV2.SqrItemProblem();
        UpSQR_ViadComDataV2.ArrayOfLookupList  ArrayOfLookupList =new UpSQR_ViadComDataV2.ArrayOfLookupList();
        UpSQR_ViadComDataV2.LookupList  LookupList =new UpSQR_ViadComDataV2.LookupList();
        UpSQR_ViadComDataV2.ArrayOfLookup  ArrayOfLookup =new UpSQR_ViadComDataV2.ArrayOfLookup();
        UpSQR_ViadComDataV2.SqrOrderLine   SqrOrderLine  =new UpSQR_ViadComDataV2.SqrOrderLine();
        UpSQR_ViadComDataV2.Lookup   Lookup  =new UpSQR_ViadComDataV2.Lookup();
        UpSQR_ViadComDataV2.SqrSummary   SqrSummary  =new UpSQR_ViadComDataV2.SqrSummary();
        UpSQR_ViadComDataV2.ArrayOfSqr    ArrayOfSqr  =new UpSQR_ViadComDataV2.ArrayOfSqr();
        UpSQR_ViadComDataV2.SqrCreateRequest   SqrCreateRequest  =new UpSQR_ViadComDataV2.SqrCreateRequest();
        UpSQR_ViadComDataV2.SimpleSqrCreateRequest   SimpleSqrCreateRequest  =new UpSQR_ViadComDataV2.SimpleSqrCreateRequest();
        UpSQR_ViadComDataV2.ArrayOfSqrTally   ArrayOfSqrTally  =new UpSQR_ViadComDataV2.ArrayOfSqrTally();
        UpSQR_ViadComDataV2.ArrayOfSqrOrderLine   ArrayOfSqrOrderLine  =new UpSQR_ViadComDataV2.ArrayOfSqrOrderLine();
        UpSQR_ViadComDataV2.ArrayOfSqrItem   ArrayOfSqrItem  =new UpSQR_ViadComDataV2.ArrayOfSqrItem();
        UpSQR_ViadComDataV2.ArrayOfSqrItemProblem   ArrayOfSqrItemProblem  =new UpSQR_ViadComDataV2.ArrayOfSqrItemProblem();
        UpSQR_ViadComDataV2.SqrDefaults   SqrDefaults  =new UpSQR_ViadComDataV2.SqrDefaults();
        UpSQR_ViadComDataV2.Sqr    Sqr   =new UpSQR_ViadComDataV2.Sqr();
        UpSQR_ViadComDataV2.SqrTally    SqrTally   =new UpSQR_ViadComDataV2.SqrTally();
        UpSQR_ViadComDataV2.SimpleSqr     SimpleSqr   =new UpSQR_ViadComDataV2.SimpleSqr();
        UpSQR_ViadComDataV2.ArrayOfSimpleSqr    ArrayOfSimpleSqr   =new UpSQR_ViadComDataV2.ArrayOfSimpleSqr();
        UpSQR_ViadComDataV2.ArrayOfSqrSummary    ArrayOfSqrSummary   =new UpSQR_ViadComDataV2.ArrayOfSqrSummary();
        UpSQR_ViadComDataV2.SqrUpdateRequest    SqrUpdateRequest   =new UpSQR_ViadComDataV2.SqrUpdateRequest();
        UpSQR_ViadComDataV2.SqrCreateMultiItemRequest    SqrCreateMultiItemRequest   =new UpSQR_ViadComDataV2.SqrCreateMultiItemRequest();
*/    
	}
}