@isTest
public class wwwViadComSecurityV2VacccVaccc_Test { 
    public static testMethod void testmethod1() {
        wwwViadComSecurityV2Vaccc.EndAppSession_element endAppSession = new wwwViadComSecurityV2Vaccc.EndAppSession_element();
        wwwViadComSecurityV2Vaccc.UserLogoutResponse_element UserLogoutResponse = new wwwViadComSecurityV2Vaccc.UserLogoutResponse_element();
        wwwViadComSecurityV2Vaccc.SearchDirectory_element SearchDirectory = new wwwViadComSecurityV2Vaccc.SearchDirectory_element();
        wwwViadComSecurityV2Vaccc.UserLogout_element UserLogout_element = new wwwViadComSecurityV2Vaccc.UserLogout_element();
        wwwViadComSecurityV2Vaccc.RequestSessionTransferResponse_element RequestSessionTransferResponse_element = new wwwViadComSecurityV2Vaccc.RequestSessionTransferResponse_element();
        wwwViadComSecurityV2Vaccc.UpdateEmailAddressResponse_element UpdateEmailAddressResponse_element = new wwwViadComSecurityV2Vaccc.UpdateEmailAddressResponse_element();
        wwwViadComSecurityV2Vaccc.UpdateContactInformationResponse_element UpdateContactInformationResponse_element = new wwwViadComSecurityV2Vaccc.UpdateContactInformationResponse_element();
        wwwViadComSecurityV2Vaccc.UserLoginByDomain_element UserLoginByDomain_element = new wwwViadComSecurityV2Vaccc.UserLoginByDomain_element();
        
        wwwViadComSecurityV2Vaccc.RequestSessionTransfer_element RequestSessionTransfer_element = new wwwViadComSecurityV2Vaccc.RequestSessionTransfer_element();
        wwwViadComSecurityV2Vaccc.AppSessionInfo AppSessionInfo = new wwwViadComSecurityV2Vaccc.AppSessionInfo();
        wwwViadComSecurityV2Vaccc.UserInfo UserInfo = new wwwViadComSecurityV2Vaccc.UserInfo();
        wwwViadComSecurityV2Vaccc.TransferSession_element TransferSession_element = new wwwViadComSecurityV2Vaccc.TransferSession_element();
        wwwViadComSecurityV2Vaccc.RetrieveContactInformationResponse_element RetrieveContactInformationResponse_element = new wwwViadComSecurityV2Vaccc.RetrieveContactInformationResponse_element();
        wwwViadComSecurityV2Vaccc.UpdateDisplayNameResponse_element  UpdateDisplayNameResponse_element = new wwwViadComSecurityV2Vaccc.UpdateDisplayNameResponse_element();
        wwwViadComSecurityV2Vaccc.QuerySession_element QuerySession_element = new wwwViadComSecurityV2Vaccc.QuerySession_element();
        wwwViadComSecurityV2Vaccc.UpdateContactInformation_element UpdateContactInformation_element = new wwwViadComSecurityV2Vaccc.UpdateContactInformation_element();
        
        wwwViadComSecurityV2Vaccc.StartAppSessionResponse_element StartAppSessionResponse_element = new wwwViadComSecurityV2Vaccc.StartAppSessionResponse_element();
        wwwViadComSecurityV2Vaccc.TransferSessionResponse_element  TransferSessionResponse_element  = new wwwViadComSecurityV2Vaccc.TransferSessionResponse_element();
        wwwViadComSecurityV2Vaccc.UserLoginResponse_element  UserLoginResponse_element  = new wwwViadComSecurityV2Vaccc.UserLoginResponse_element();
        wwwViadComSecurityV2Vaccc.ResetPasswordRequestInfo  ResetPasswordRequestInfo  = new wwwViadComSecurityV2Vaccc.ResetPasswordRequestInfo ();
        wwwViadComSecurityV2Vaccc.UserLogin_element  UserLogin_element  = new wwwViadComSecurityV2Vaccc.UserLogin_element();
        wwwViadComSecurityV2Vaccc.UserLoginWithoutPasswordResponse_element   UserLoginWithoutPasswordResponse_element  = new wwwViadComSecurityV2Vaccc.UserLoginWithoutPasswordResponse_element();
        wwwViadComSecurityV2Vaccc.ArrayOfDirectoryInfo  ArrayOfDirectoryInfo  = new wwwViadComSecurityV2Vaccc.ArrayOfDirectoryInfo ();
        wwwViadComSecurityV2Vaccc.ResetPassword_element  ResetPassword_element  = new wwwViadComSecurityV2Vaccc.ResetPassword_element ();
        
        wwwViadComSecurityV2Vaccc.ResetPasswordResponse_element  ResetPasswordResponse_element  = new wwwViadComSecurityV2Vaccc.ResetPasswordResponse_element ();
        wwwViadComSecurityV2Vaccc.DomainInfo   DomainInfo   = new wwwViadComSecurityV2Vaccc.DomainInfo ();
        wwwViadComSecurityV2Vaccc.ContactInfo   ContactInfo   = new wwwViadComSecurityV2Vaccc.ContactInfo ();
        wwwViadComSecurityV2Vaccc.SearchDirectoryResponse_element   SearchDirectoryResponse_element   = new wwwViadComSecurityV2Vaccc.SearchDirectoryResponse_element  ();
        wwwViadComSecurityV2Vaccc.UserLoginWithStoredPasswordResponse_element   UserLoginWithStoredPasswordResponse_element   = new wwwViadComSecurityV2Vaccc.UserLoginWithStoredPasswordResponse_element ();
        wwwViadComSecurityV2Vaccc.UserLoginWithStoredPassword_element    UserLoginWithStoredPassword_element   = new wwwViadComSecurityV2Vaccc.UserLoginWithStoredPassword_element ();
        wwwViadComSecurityV2Vaccc.QuerySessionResponse_element   QuerySessionResponse_element   = new wwwViadComSecurityV2Vaccc.QuerySessionResponse_element  ();
        wwwViadComSecurityV2Vaccc.ArrayOfResetPasswordRequestInfo   ArrayOfResetPasswordRequestInfo   = new wwwViadComSecurityV2Vaccc.ArrayOfResetPasswordRequestInfo  ();
        
        wwwViadComSecurityV2Vaccc.UserLoginWithoutPassword_element   UserLoginWithoutPassword_element   = new wwwViadComSecurityV2Vaccc.UserLoginWithoutPassword_element  ();
        wwwViadComSecurityV2Vaccc.UpdateEmailAddress_element    UpdateEmailAddress_element    = new wwwViadComSecurityV2Vaccc.UpdateEmailAddress_element  ();
        wwwViadComSecurityV2Vaccc.UserLoginByDomainResponse_element    UserLoginByDomainResponse_element    = new wwwViadComSecurityV2Vaccc.UserLoginByDomainResponse_element  ();
        wwwViadComSecurityV2Vaccc.UpdateDisplayName_element    UpdateDisplayName_element    = new wwwViadComSecurityV2Vaccc.UpdateDisplayName_element   ();
        wwwViadComSecurityV2Vaccc.EndAppSessionResponse_element    EndAppSessionResponse_element    = new wwwViadComSecurityV2Vaccc.EndAppSessionResponse_element  ();
        wwwViadComSecurityV2Vaccc.QueryOtherSession_element     QueryOtherSession_element    = new wwwViadComSecurityV2Vaccc.QueryOtherSession_element  ();
        wwwViadComSecurityV2Vaccc.RetrieveContactInformation_element    RetrieveContactInformation_element    = new wwwViadComSecurityV2Vaccc.RetrieveContactInformation_element   ();
        wwwViadComSecurityV2Vaccc.StartAppSession_element    StartAppSession_element    = new wwwViadComSecurityV2Vaccc.StartAppSession_element   ();
        
        wwwViadComSecurityV2Vaccc.ResetPasswordRequestResponse_element    ResetPasswordRequestResponse_element    = new wwwViadComSecurityV2Vaccc.ResetPasswordRequestResponse_element   ();
        wwwViadComSecurityV2Vaccc.DirectoryInfo     DirectoryInfo     = new wwwViadComSecurityV2Vaccc.DirectoryInfo   ();
        wwwViadComSecurityV2Vaccc.CreateAccount_element     CreateAccount_element     = new wwwViadComSecurityV2Vaccc.CreateAccount_element   ();
        wwwViadComSecurityV2Vaccc.CreateAccountResponse_element     CreateAccountResponse_element     = new wwwViadComSecurityV2Vaccc.CreateAccountResponse_element    ();
        wwwViadComSecurityV2Vaccc.ResetPasswordRequest_element     ResetPasswordRequest_element     = new wwwViadComSecurityV2Vaccc.ResetPasswordRequest_element   ();
        wwwViadComSecurityV2Vaccc.QueryOtherSessionResponse_element      QueryOtherSessionResponse_element     = new wwwViadComSecurityV2Vaccc.QueryOtherSessionResponse_element   ();
        wwwViadComSecurityV2Vaccc.ArrayOfDomainInfo     ArrayOfDomainInfo     = new wwwViadComSecurityV2Vaccc.ArrayOfDomainInfo    ();
        
        wwwViadComSecurityV2Vaccc.BasicHttpBinding_IAuthenticationService     BasicHttpBinding_IAuthenticationService     = new wwwViadComSecurityV2Vaccc.BasicHttpBinding_IAuthenticationService    ();
       Test.setMock(WebServiceMock.class, new wwwViadComSecurityV2VacccVaccc_Mock());
        BasicHttpBinding_IAuthenticationService.ResetPasswordRequest('testlogin', 'testlogin', 'test@test.com');
        BasicHttpBinding_IAuthenticationService.UserLoginWithoutPassword('testlogin','test@test.com', true);
        BasicHttpBinding_IAuthenticationService.StartAppSession('testlogin','test@test.com', 'true','test');
        BasicHttpBinding_IAuthenticationService.RetrieveContactInformation('testlogin');
        
        BasicHttpBinding_IAuthenticationService.SearchDirectory('testlogin','testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.UserLogin ('testlogin','testlogin','testlogin', true);
        BasicHttpBinding_IAuthenticationService.UserLoginWithStoredPassword ('testlogin','testlogin','testlogin','password', true);
        BasicHttpBinding_IAuthenticationService.TransferSession ('testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.ResetPassword ('testlogin','testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.UpdateEmailAddress ('testlogin','testlogin@test.com');
        BasicHttpBinding_IAuthenticationService.UpdateDisplayName ('testlogin','Rahul');
        BasicHttpBinding_IAuthenticationService.QuerySession ('testlogin');
        BasicHttpBinding_IAuthenticationService.UserLoginByDomain ('testlogin','Rahul','loginName','password',true);
        BasicHttpBinding_IAuthenticationService.QueryOtherSession ('testlogin','Rahul');
                
    } 
}