@isTest
public class wwwViadComSecurityV2_Test {
    public static testMethod void testmethod1() {
        wwwViadComSecurityV2.EndAppSession_element endAppSession = new wwwViadComSecurityV2.EndAppSession_element();
        wwwViadComSecurityV2.UserLogoutResponse_element UserLogoutResponse = new wwwViadComSecurityV2.UserLogoutResponse_element();
        wwwViadComSecurityV2.SearchDirectory_element SearchDirectory = new wwwViadComSecurityV2.SearchDirectory_element();
        wwwViadComSecurityV2.UserLogout_element UserLogout_element = new wwwViadComSecurityV2.UserLogout_element();
        wwwViadComSecurityV2.RequestSessionTransferResponse_element RequestSessionTransferResponse_element = new wwwViadComSecurityV2.RequestSessionTransferResponse_element();
        wwwViadComSecurityV2.UpdateEmailAddressResponse_element UpdateEmailAddressResponse_element = new wwwViadComSecurityV2.UpdateEmailAddressResponse_element();
        wwwViadComSecurityV2.UpdateContactInformationResponse_element UpdateContactInformationResponse_element = new wwwViadComSecurityV2.UpdateContactInformationResponse_element();
        wwwViadComSecurityV2.UserLoginByDomain_element UserLoginByDomain_element = new wwwViadComSecurityV2.UserLoginByDomain_element();
        
        wwwViadComSecurityV2.RequestSessionTransfer_element RequestSessionTransfer_element = new wwwViadComSecurityV2.RequestSessionTransfer_element();
        wwwViadComSecurityV2.AppSessionInfo AppSessionInfo = new wwwViadComSecurityV2.AppSessionInfo();
        wwwViadComSecurityV2.UserInfo UserInfo = new wwwViadComSecurityV2.UserInfo();
        wwwViadComSecurityV2.TransferSession_element TransferSession_element = new wwwViadComSecurityV2.TransferSession_element();
        wwwViadComSecurityV2.RetrieveContactInformationResponse_element RetrieveContactInformationResponse_element = new wwwViadComSecurityV2.RetrieveContactInformationResponse_element();
        wwwViadComSecurityV2.UpdateDisplayNameResponse_element  UpdateDisplayNameResponse_element = new wwwViadComSecurityV2.UpdateDisplayNameResponse_element();
        wwwViadComSecurityV2.QuerySession_element QuerySession_element = new wwwViadComSecurityV2.QuerySession_element();
        wwwViadComSecurityV2.UpdateContactInformation_element UpdateContactInformation_element = new wwwViadComSecurityV2.UpdateContactInformation_element();
        
        wwwViadComSecurityV2.StartAppSessionResponse_element StartAppSessionResponse_element = new wwwViadComSecurityV2.StartAppSessionResponse_element();
        wwwViadComSecurityV2.TransferSessionResponse_element  TransferSessionResponse_element  = new wwwViadComSecurityV2.TransferSessionResponse_element();
        wwwViadComSecurityV2.UserLoginResponse_element  UserLoginResponse_element  = new wwwViadComSecurityV2.UserLoginResponse_element();
        wwwViadComSecurityV2.ResetPasswordRequestInfo  ResetPasswordRequestInfo  = new wwwViadComSecurityV2.ResetPasswordRequestInfo ();
        wwwViadComSecurityV2.UserLogin_element  UserLogin_element  = new wwwViadComSecurityV2.UserLogin_element();
        wwwViadComSecurityV2.UserLoginWithoutPasswordResponse_element   UserLoginWithoutPasswordResponse_element  = new wwwViadComSecurityV2.UserLoginWithoutPasswordResponse_element();
        wwwViadComSecurityV2.ArrayOfDirectoryInfo  ArrayOfDirectoryInfo  = new wwwViadComSecurityV2.ArrayOfDirectoryInfo ();
        wwwViadComSecurityV2.ResetPassword_element  ResetPassword_element  = new wwwViadComSecurityV2.ResetPassword_element ();
        
        wwwViadComSecurityV2.ResetPasswordResponse_element  ResetPasswordResponse_element  = new wwwViadComSecurityV2.ResetPasswordResponse_element ();
        wwwViadComSecurityV2.DomainInfo   DomainInfo   = new wwwViadComSecurityV2.DomainInfo ();
        wwwViadComSecurityV2.ContactInfo   ContactInfo   = new wwwViadComSecurityV2.ContactInfo ();
        wwwViadComSecurityV2.SearchDirectoryResponse_element   SearchDirectoryResponse_element   = new wwwViadComSecurityV2.SearchDirectoryResponse_element  ();
        wwwViadComSecurityV2.UserLoginWithStoredPasswordResponse_element   UserLoginWithStoredPasswordResponse_element   = new wwwViadComSecurityV2.UserLoginWithStoredPasswordResponse_element ();
        wwwViadComSecurityV2.UserLoginWithStoredPassword_element    UserLoginWithStoredPassword_element   = new wwwViadComSecurityV2.UserLoginWithStoredPassword_element ();
        wwwViadComSecurityV2.QuerySessionResponse_element   QuerySessionResponse_element   = new wwwViadComSecurityV2.QuerySessionResponse_element  ();
        wwwViadComSecurityV2.ArrayOfResetPasswordRequestInfo   ArrayOfResetPasswordRequestInfo   = new wwwViadComSecurityV2.ArrayOfResetPasswordRequestInfo  ();
        
        wwwViadComSecurityV2.UserLoginWithoutPassword_element   UserLoginWithoutPassword_element   = new wwwViadComSecurityV2.UserLoginWithoutPassword_element  ();
        wwwViadComSecurityV2.UpdateEmailAddress_element    UpdateEmailAddress_element    = new wwwViadComSecurityV2.UpdateEmailAddress_element  ();
        wwwViadComSecurityV2.UserLoginByDomainResponse_element    UserLoginByDomainResponse_element    = new wwwViadComSecurityV2.UserLoginByDomainResponse_element  ();
        wwwViadComSecurityV2.UpdateDisplayName_element    UpdateDisplayName_element    = new wwwViadComSecurityV2.UpdateDisplayName_element   ();
        wwwViadComSecurityV2.EndAppSessionResponse_element    EndAppSessionResponse_element    = new wwwViadComSecurityV2.EndAppSessionResponse_element  ();
        wwwViadComSecurityV2.QueryOtherSession_element     QueryOtherSession_element    = new wwwViadComSecurityV2.QueryOtherSession_element  ();
        wwwViadComSecurityV2.RetrieveContactInformation_element    RetrieveContactInformation_element    = new wwwViadComSecurityV2.RetrieveContactInformation_element   ();
        wwwViadComSecurityV2.StartAppSession_element    StartAppSession_element    = new wwwViadComSecurityV2.StartAppSession_element   ();
        
        wwwViadComSecurityV2.ResetPasswordRequestResponse_element    ResetPasswordRequestResponse_element    = new wwwViadComSecurityV2.ResetPasswordRequestResponse_element   ();
        wwwViadComSecurityV2.DirectoryInfo     DirectoryInfo     = new wwwViadComSecurityV2.DirectoryInfo   ();
        wwwViadComSecurityV2.CreateAccount_element     CreateAccount_element     = new wwwViadComSecurityV2.CreateAccount_element   ();
        wwwViadComSecurityV2.CreateAccountResponse_element     CreateAccountResponse_element     = new wwwViadComSecurityV2.CreateAccountResponse_element    ();
        wwwViadComSecurityV2.ResetPasswordRequest_element     ResetPasswordRequest_element     = new wwwViadComSecurityV2.ResetPasswordRequest_element   ();
        wwwViadComSecurityV2.QueryOtherSessionResponse_element      QueryOtherSessionResponse_element     = new wwwViadComSecurityV2.QueryOtherSessionResponse_element   ();
        wwwViadComSecurityV2.ArrayOfDomainInfo     ArrayOfDomainInfo     = new wwwViadComSecurityV2.ArrayOfDomainInfo    ();
        
        wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService     BasicHttpBinding_IAuthenticationService     = new wwwViadComSecurityV2.BasicHttpBinding_IAuthenticationService    ();
        Test.setMock(WebServiceMock.class, new wwwViadComSecurityV2_Mock());
        BasicHttpBinding_IAuthenticationService.ResetPasswordRequest('testlogin', 'testlogin', 'test@test.com');
        BasicHttpBinding_IAuthenticationService.UserLoginWithoutPassword('testlogin','test@test.com', true);
        BasicHttpBinding_IAuthenticationService.StartAppSession('testlogin','test@test.com', 'true','test');
        BasicHttpBinding_IAuthenticationService.RetrieveContactInformation('testlogin');
        
        BasicHttpBinding_IAuthenticationService.SearchDirectory('testlogin','testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.UserLogin ('testlogin','testlogin','testlogin', true);
        BasicHttpBinding_IAuthenticationService.UserLoginWithStoredPassword ('testlogin','testlogin','testlogin','password', true);
        BasicHttpBinding_IAuthenticationService.TransferSession ('testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.ResetPassword ('testlogin','testlogin','testlogin');
        BasicHttpBinding_IAuthenticationService.UpdateEmailAddress ('testlogin','testlogin@test.com');
        BasicHttpBinding_IAuthenticationService.UpdateDisplayName ('testlogin','Rahul');
        BasicHttpBinding_IAuthenticationService.QuerySession ('testlogin');
        BasicHttpBinding_IAuthenticationService.UserLoginByDomain ('testlogin','Rahul','loginName','password',true);
        BasicHttpBinding_IAuthenticationService.QueryOtherSession ('testlogin','Rahul');
        
        
        
    } 
}